language: python
cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

install:
  - python setup.py develop
  - pip install -r requirements-test.txt

before_script:
  - openwisp-utils-qa-checks --skip-checkmigrations --skip-checkmakemigrations

script:
  - nose2 --with-coverage --coverage=netdiff

after_success:
  coveralls
